# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 28
# Label requiring a response
responseRequiredLabel: needs-info
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  This issue has been automatically closed due to lack of information. If you have further details, please feel free to re-open the issue.
