name: Automate project columns

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move new issues into project
        uses: alex-page/github-project-automation-plus@master
        with:
          project: 27th September - 7th November
          column: To do
          repo-token: ${{ secrets.GH_PAT }}
